name: Android CI

env:
  main_project_module: app
  playstore_name: Island

on:
  push:
    branches:
      - 'dev' # Only trigger on 'dev' branch pushes
  pull_request:
    branches:
      - 'dev' # Only trigger on 'dev' branch pull requests
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables for analytics
        run: echo "DISABLE_ANALYTICS=true" >> $GITHUB_ENV

      - name: Checkout deagle repository (dev branch)
        uses: actions/checkout@v4
        with:
          repository: 'oasisfeng/deagle'
          path: 'deagle'
          ref: 'dev' # Explicitly checkout the 'dev' branch of deagle

      - name: Checkout main app code (dev branch)
        uses: actions/checkout@v4
        with:
          path: 'island' # Checkout the main app into the 'island' folder
          ref: 'dev' # Explicitly checkout the 'dev' branch of the main app repository

      # IMPORTANT: Place Set Up JDK BEFORE any Gradle commands
      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      # These steps now run *after* Java 17 is set up
      - name: Ensure Gradle wrapper is executable
        # Assuming gradlew is now in the 'island' directory
        run: chmod +x island/gradlew

      - name: Verify Gradle wrapper version
        # Assuming gradlew is now in the 'island' directory
        run: island/gradlew --version # This should now show Gradle 8.8 (or whatever you set)

      - name: Run gradle tests
        # Assuming gradlew is now in the 'island' directory
        run: island/gradlew test

      - name: Build gradle project
        # Assuming gradlew is now in the 'island' directory
        run: island/gradlew build

      - name: Build APK Debug - ${{ env.main_project_module }}
        # Assuming gradlew is now in the 'island' directory
        run: island/gradlew assembleDebug -PdisableAnalytics=true

      - name: Build app with analytics disabled (Release)
        # Assuming gradlew is now in the 'island' directory
        run: island/gradlew assembleRelease -PdisableAnalytics=true

      - name: Build App Bundle (AAB) Release - ${{ env.main_project_module }}
        # Assuming gradlew is now in the 'island' directory
        run: island/gradlew ${{ env.main_project_module }}:bundleRelease

      - name: Upload APK Debug Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) debug generated
          # Path adjusted for 'island' directory
          path: island/${{ env.main_project_module }}/build/outputs/apk/debug/

      - name: Upload APK Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) release generated
          # Path adjusted for 'island' directory
          path: island/${{ env.main_project_module }}/build/outputs/apk/release/

      - name: Upload AAB (App Bundle) Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - App bundle(s) AAB release generated
          # Path adjusted for 'island' directory
          path: island/${{ env.main_project_module }}/build/outputs/bundle/release/
